import time

print("hello")
print("hello2")
print("hello3")
time.sleep(1)
print("hello")
print("hello2")
print("hello3")
time.sleep(1)
print("hello")
print("hello2")
print("hello3")
time.sleep(1)
print("hello")
print("hello2")
print("hello3")
time.sleep(1)
print("hello")
print("hello2")
print("hello3")
time.sleep(1)