import time

print("hello")
print("привет")
print("че как")
time.sleep(1)
print("hello")
print("привет")
print("че как")
time.sleep(1)
print("hello")
print("привет")
print("че как")
time.sleep(1)
print("hello")
print("привет")
print("че как")
time.sleep(1)
print("hello")
print("привет")
print("че как")
time.sleep(1)